#!/bin/bash
if [ -z "$1" ]; then
  echo No argument given 
  exit
fi

TOKEN=<TOKEN>
CHAT_ID=<CHAT_ID>
Message=$1
FilePath=$2

CMD1="https://api.telegram.org/bot$TOKEN/sendMessage"
CMD2="https://api.telegram.org/bot$TOKEN/sendDocument"

if [ -n "$FilePath" ]; then
	curl $CMD2 -F chat_id=$CHAT_ID -F document=@"$FilePath" -F caption="$Message" >/dev/null 2>&1
else
	curl -s -X POST $CMD1 -d chat_id=$CHAT_ID -d text="$Message" >/dev/null 2>&1
fi
